name = "ForAdem"
version = "0.1.0"
defaultTargets = ["foradem"]
moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "main"

[[lean_lib]]
name = "ForAdem"

[[lean_exe]]
name = "foradem"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"
